# Configuration pre-commit pour TradePulse ML
# Synchronisé avec la CI GitHub Actions (sans Black)

repos:
  # 1. isort - Tri des imports (identique à la CI)  
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: ^scripts/.*\.py$
        name: "isort (Import sorter)"
        description: "Sort Python imports"

  # 2. Ruff - Linting rapide (identique à la CI)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: ["--fix"]
        files: ^scripts/.*\.py$
        name: "Ruff (Fast linter)"
        description: "Fast Python linter with auto-fix"

  # 3. Contrôles supplémentaires utiles
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        name: "Remove trailing whitespace"
      - id: end-of-file-fixer
        name: "Fix end of files"
      - id: check-yaml
        name: "Check YAML syntax"
        files: \.(yaml|yml)$
      - id: check-json
        name: "Check JSON syntax"
      - id: check-added-large-files
        name: "Check for large files"
        args: ['--maxkb=10240']  # 10MB max
      - id: check-merge-conflict
        name: "Check for merge conflicts"

# Configuration globale
default_language_version:
  python: python3.9

# Optimisations
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
