# Configuration d'entraînement FinBERT

model:
  base_model: "yiyanghkust/finbert-tone"
  num_labels: 3
  problem_type: "single_label_classification"

training:
  learning_rate: 2e-5
  num_train_epochs: 3
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 32
  warmup_steps: 100
  weight_decay: 0.01
  logging_steps: 50
  eval_steps: 200
  save_steps: 500
  evaluation_strategy: "steps"
  save_strategy: "steps"
  load_best_model_at_end: true
  metric_for_best_model: "f1"
  greater_is_better: true

data:
  max_length: 512
  train_file: "datasets/labeled/train.csv"
  eval_file: "datasets/labeled/eval.csv"
  test_file: "datasets/labeled/test.csv"
  text_column: "text"
  label_column: "label"

output:
  output_dir: "models/experiments"
  logging_dir: "logs"
  run_name: "finbert-sentiment"

labels:
  label_names: ["negative", "neutral", "positive"]
  label2id:
    negative: 0
    neutral: 1  
    positive: 2
  id2label:
    0: "negative"
    1: "neutral"
    2: "positive"
